{
 "title": "Blackbox ICMP",
 "description": "Graph ICMP metrics from the blackbox exporter, Smokeping-style",
 "tags": [
  "prometheus",
  "blackbox"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(probe_icmp_duration_seconds, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ICMP RTT",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{phase=\"rtt\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "$instance Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "instance" },
  {
   "title": "ICMP packet loss",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "1-avg_over_time(probe_success{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ICMP round trip time ($instance)",
   "type": "graph",
   "description": "This uses the blackbox exporter, which does not expose packet loss, for example. It could be improved with https://github.com/SuperQ/smokeping_prober because it also keeps track of lost samples (https://github.com/SuperQ/smokeping_prober/issues/24). Unfortunately, that still won't make graphs as nice as smokeping, because each probe only keeps one sample, instead of doing multiple like smokeping does (https://github.com/SuperQ/smokeping_prober/issues/36).",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "dtdurations", "label": "RTT" }
   ],
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{phase=\"rtt\",instance=~\"$instance\"}) by (instance) > 0",
     "legendFormat": "RTT"
    },
    {
     "expr": "1-avg_over_time(probe_success{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "packet loss"
    }
   ]
  }
 ]
}