{
 "title": "Kasa",
 "tags": [
  "Kasa",
  "Prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(kasa_power_load, instance)"
   },
   { "name": "electricity_cost", "query": "0.1337" }
  ]
 },
 "panels": [
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "kasa_power_load{instance=~\"$host\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Online",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kasa_online==1)/count(kasa_online)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "kasa_voltage{instance=~\"$host\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Power",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kasa_power_load{instance=~\"$host\"}) by (job)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Ampere",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "kasa_current{instance=~\"$host\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Last 30 Days",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(kasa_power_total{instance=~\"$host\"}[30d])) by (job)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "expr": "kasa_rssi{instance=~\"$host\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Last 30 Days - Total Cost",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(kasa_power_total{instance=~\"$host\"}[30d])) by (job)*$electricity_cost",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}