{
 "title": "PDNS recursor",
 "description": "PowerDNS Recursor built-in exporter stats",
 "tags": [
  "Prometheus",
  "Powerdns"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "T",
    "label": "Interval",
    "query": "1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "host",
    "query": "label_values({__name__=~\"pdns_recursor.*\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Answers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(pdns_recursor_answers0_1{instance=~\"$host\"}[$T]))",
     "legendFormat": "0-1 ms"
    },
    {
     "expr": "sum (rate(pdns_recursor_answers1_10{instance=~\"$host\"}[$T]))",
     "legendFormat": "1-10 ms"
    },
    {
     "expr": "sum (rate(pdns_recursor_answers10_100{instance=~\"$host\"}[$T]))",
     "legendFormat": "10-100 ms"
    },
    {
     "expr": "sum  (rate(pdns_recursor_answers100_1000{instance=~\"$host\"}[$T]))",
     "legendFormat": "100-1000 ms"
    },
    {
     "expr": "sum (rate(pdns_recursor_answers_slow{job=\"pdns-rec\",instance=~\"($recursor).+\"}[$T]))",
     "legendFormat": "slow"
    }
   ]
  },
  {
   "title": "Cache hits/miss ratio",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(pdns_recursor_cache_hits{instance=~\"$host\"}[$__range]))",
     "legendFormat": "hits"
    },
    {
     "expr": "sum(increase(pdns_recursor_cache_misses{instance=~\"$host\"}[$__range]))",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "title": "All outqueries",
   "type": "graph",
   "description": "Number of outgoing UDP queries since starting",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pdns_recursor_all_outqueries{instance=~\"$host\"}[$T])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "All IPv6 outqueries",
   "type": "graph",
   "description": "Number of outgoing queries  via IPv6 since starting",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pdns_recursor_ipv6_outqueries{instance=~\"$host\"}[$T])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Answers auth4",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pdns_recursor_auth4_answers0_1{instance=~\"$host\"}[$T]))",
     "legendFormat": "0-1 ms"
    },
    {
     "expr": "sum(rate(pdns_recursor_auth4_answers1_10{instance=~\"$host\"}[$T]))",
     "legendFormat": "1-10 ms"
    },
    {
     "expr": "sum(rate(pdns_recursor_auth4_answers10_100{instance=~\"$host\"}[$T]))",
     "legendFormat": "10-100 ms"
    },
    {
     "expr": "sum(rate(pdns_recursor_auth4_answers100_1000{instance=~\"$host\"}[$T]))",
     "legendFormat": "100-1000 ms"
    },
    {
     "expr": "sum(rate(pdns_recursor_auth4_answers_slow{instance=~\"$host\"}[$T]))",
     "legendFormat": "slow"
    }
   ]
  },
  {
   "title": "Answers auth6",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(pdns_recursor_auth6_answers0_1{instance=~\"$host\"}[$T]))",
     "legendFormat": "0-1 ms"
    },
    {
     "expr": "sum  (rate(pdns_recursor_auth6_answers1_10{instance=~\"$host\"}[$T]))",
     "legendFormat": "1-10 ms"
    },
    {
     "expr": "sum (rate(pdns_recursor_auth6_answers10_100{instance=~\"$host\"}[$T]))",
     "legendFormat": "10-100 ms"
    },
    {
     "expr": "sum (rate(pdns_recursor_auth6_answers100_1000{instance=~\"$host\"}[$T]))",
     "legendFormat": "100-1000 ms"
    },
    {
     "expr": "sum (rate(pdns_recursor_auth6_answers_slow{job=\"pdns-rec\",instance=~\"($recursor).+\"}[$T]))",
     "legendFormat": "slow"
    }
   ]
  },
  {
   "title": "Questions All",
   "type": "graph",
   "description": "counts all end-user initiated queries with the RD bit set",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pdns_recursor_questions{instance=~\"$host\"}[$T]) + rate(pdns_recursor_ipv6_questions{instance=~\"$host\"}[$T])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Failed events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(pdns_recursor_servfail_answers{instance=~\"$host\"}[$T]))",
     "legendFormat": "SERVFAIL"
    },
    {
     "expr": "sum (rate(pdns_recursor_nxdomain_answers{instance=~\"$host\"}[$T]))",
     "legendFormat": "NXDomain"
    },
    {
     "expr": "sum (rate(pdns_recursor_failed_host_entries{instance=~\"$host\"}[$T]))",
     "legendFormat": "Failed host"
    },
    {
     "expr": "sum (rate(pdns_recursor_unauthorized_udp{instance=~\"$host\"}[$T]))",
     "legendFormat": "Unauthorized UDP"
    },
    {
     "expr": "sum (rate(pdns_recursor_outgoing_timeouts{job=\"pdns-rec\",instance=~\"($recursor).+\"}[$T]))",
     "legendFormat": "Timeout"
    },
    {
     "expr": "sum (rate(pdns_recursor_policy_result_noaction{job=\"pdns-rec\",instance=~\"($recursor).+\"}[$T]))",
     "legendFormat": "No action"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pdns_recursor_cache_hits{instance=~\"$host\"}[$T]))",
     "legendFormat": "hits"
    },
    {
     "expr": "sum(rate(pdns_recursor_cache_misses{instance=~\"$host\"}[$T]))",
     "legendFormat": "misses"
    },
    {
     "expr": "sum(rate(pdns_recursor_cache_entries{instance=~\"$host\"}[$T]))",
     "legendFormat": "entries"
    },
    {
     "expr": "sum(rate(pdns_recursor_negcache_entries{instance=~\"$host\"}[$T]))",
     "legendFormat": "negative"
    }
   ]
  },
  {
   "title": "DNSSEC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(pdns_recursor_dnssec_queries{instance=~\"$host\"}[$T]))",
     "legendFormat": "Querries"
    },
    {
     "expr": "sum (rate(pdns_recursor_dnssec_check_disabled_queries{instance=~\"$host\"}[$T]))",
     "legendFormat": "Querries check disabled"
    }
   ]
  },
  {
   "title": "CPU msec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pdns_recursor_cpu_msec_thread_0{instance=~\"$host\"}[$T]))",
     "legendFormat": "CPU thread 0"
    },
    {
     "expr": "sum(rate(pdns_recursor_cpu_msec_thread_1{instance=~\"$host\"}[$T]))",
     "legendFormat": "CPU thread 1"
    },
    {
     "expr": "sum(rate(pdns_recursor_cpu_msec_thread_2{instance=~\"$host\"}[$T]))",
     "legendFormat": "CPU thread 2"
    },
    {
     "expr": "sum(rate(pdns_recursor_sys_msec{instance=~\"$host\"}[$T]))",
     "legendFormat": "System mode"
    },
    {
     "expr": "sum(rate(pdns_recursor_user_msec{instance=~\"$host\"}[$T]))",
     "legendFormat": "User mode"
    }
   ]
  }
 ]
}