{
 "title": "QNAP",
 "description": "Simple QNAP Dashboard\r\n* System CPU and Memory Usage\r\n* Volume Size\r\n* Network stats\r\n* Cache Stats (if a SSD Cache card is present)\r\n* System and Disks temperature",
 "tags": [
  "Prometheus",
  "SNMP",
  "QNAP"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "label_values(sysVolumeTotalSizeEX, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sysUpTime{instance=~\"$host\"}/100"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sysVolumeTotalSizeEX{instance=~\"$host\"} - sysVolumeFreeSizeEX{instance=~\"$host\"}) / sysVolumeTotalSizeEX{instance=~\"$host\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Volume status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sysVolumeStatusEX{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Smart info",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hdSmartInfo{instance=~\"$host\"}",
     "legendFormat": "{{ hdDescr }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "systemCPU_UsageEX{instance=~\"$host\"}",
     "legendFormat": "System Usage"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "systemFreeMem{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Disk temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "degree" }
   ],
   "targets": [
    {
     "expr": "hdTemperatureEX{instance=~\"$host\"}",
     "legendFormat": "{{ hdDescr }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{instance=~\"$host\"}[15m])",
     "legendFormat": "Out: {{ ifName }}"
    },
    {
     "expr": "-irate(ifHCInOctets{instance=~\"$host\"}[15m])",
     "legendFormat": "In: {{ ifName }}"
    }
   ]
  }
 ]
}