{
 "title": "Runrestic",
 "description": "Show status of Restic backups (wrapped with runrestic)",
 "tags": [
  "Prometheus",
  "runrestic"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "config",
    "label": "config",
    "query": {
     "query": "label_values(restic_total_duration_seconds,config)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Config specific", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "config" },
  {
   "title": "Durations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "restic_stats_duration_seconds{config=\"$config\"}",
     "legendFormat": "stats"
    },
    {
     "expr": "restic_backup_processed_duration_seconds{config=\"$config\"}",
     "legendFormat": "backup processed"
    },
    {
     "expr": "restic_check_duration_seconds{config=\"$config\"}",
     "legendFormat": "check"
    },
    {
     "expr": "restic_prune_duration_seconds{config=\"$config\"}",
     "legendFormat": "prune"
    }
   ]
  },
  {
   "title": "Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "restic_stats_total_size_bytes{config=\"$config\"}",
     "legendFormat": "total size in restore mode"
    },
    {
     "expr": "restic_backup_processed_size_bytes{config=\"$config\"}",
     "legendFormat": "backup processed"
    },
    {
     "expr": "restic_prune_containing_size_bytes{config=\"$config\"}",
     "legendFormat": "repository containing"
    },
    {
     "expr": "restic_prune_duplicate_size_bytes{config=\"$config\"}",
     "legendFormat": "repository duplicate"
    }
   ]
  },
  {
   "title": "Number of files",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "restic_backup_files_changed{config=\"$config\"}",
     "legendFormat": "changed"
    },
    {
     "expr": "restic_backup_files_new{config=\"$config\"}",
     "legendFormat": "new"
    },
    {
     "expr": "restic_backup_files_unmodified{config=\"$config\"}",
     "legendFormat": "unmodified"
    },
    {
     "expr": "restic_backup_processed_files{config=\"$config\"}",
     "legendFormat": "processed"
    }
   ]
  },
  { "title": "Success & Fail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Failed",
   "type": "stat",
   "description": "Number of runrestic backup commands with a failed return code",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(restic_backup_rc)" }
   ]
  },
  {
   "title": "Success & fails",
   "type": "graph",
   "description": "Number of runrestic backup commands with a successful return code",
   "gridPos": { "h": 4, "w": 11, "x": 2, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count by (config) (restic_backup_rc == 0))"
    },
    {
     "expr": "sum(count by (config) (restic_backup_rc != 0))"
    }
   ]
  },
  {
   "title": "Fail",
   "type": "table",
   "description": "Number of runrestic backup commands with a unsuccessful return code",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 9 },
   "targets": [
    {
     "expr": "sum(restic_backup_rc != 0) by (config)",
     "legendFormat": "{{ config }}"
    }
   ]
  },
  {
   "title": "Successful",
   "type": "stat",
   "description": "Number of runrestic backup commands with a successful return code",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (config) (restic_backup_rc == 0))"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Total Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "restic_total_duration_seconds", "legendFormat": "{{ config }}" }
   ]
  },
  {
   "title": "Processed size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "restic_backup_processed_size_bytes",
     "legendFormat": "{{ config }}"
    }
   ]
  }
 ]
}