{
 "title": "SNMP Interface Detail",
 "description": "Detailed interface stats from prometheus snmp exporter",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "source", "label": "Source", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(ifOperStatus, instance)"
    }
   },
   {
    "name": "ifName",
    "query": {
     "query": "query_result(ifOperStatus{instance=\"$instance\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Admin Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ifAdminStatus{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "title": "Oper Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ifOperStatus{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "title": "Last Change",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "timeticks",
   "valueName": "current",
   "targets": [
    {
     "expr": "sysUpTime{instance=\"$instance\"} - on(instance) ifLastChange{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "title": "Connector Present",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ifConnectorPresent{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "title": "Promiscuous Mode",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ifPromiscuousMode{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "ifHighSpeed{instance=\"$instance\",ifName=\"$ifName\"}*1000000 or ifSpeed{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "title": "MTU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ifMtu{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "type": "table-old",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "ifType_info{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "(irate(ifHCInOctets{instance=\"$instance\",ifName=\"$ifName\"}[2m]) or irate(ifInOctets{instance=\"$instance\",ifName=\"$ifName\"}[2m]))*8",
     "legendFormat": "IN: {{ifName}}"
    },
    {
     "expr": "(irate(ifHCOutOctets{instance=\"$instance\",ifName=\"$ifName\"}[2m]) or irate(ifOutOctets{instance=\"$instance\",ifName=\"$ifName\"}[2m]))*8",
     "legendFormat": "OUT: {{ifName}}"
    }
   ]
  },
  {
   "title": "Unicast Packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInUcastPkts{instance=\"$instance\",ifName=\"$ifName\"}[2m]) or irate(ifInUcastPkts{instance=\"$instance\",ifName=\"$ifName\"}[2m])",
     "legendFormat": "IN: {{ifName}}"
    },
    {
     "expr": "irate(ifHCOutUcastPkts{instance=\"$instance\",ifName=\"$ifName\"}[2m]) or irate(ifOutUcastPkts{instance=\"$instance\",ifName=\"$ifName\"}[2m])",
     "legendFormat": "OUT: {{ifName}}"
    }
   ]
  },
  {
   "title": "Broadcast Packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInBroadcastPkts{instance=\"$instance\",ifName=\"$ifName\"}[2m]) or irate(ifInBroadcastPkts{instance=\"$instance\",ifName=\"$ifName\"}[2m])",
     "legendFormat": "IN: {{ifName}}"
    },
    {
     "expr": "irate(ifHCOutBroadcastPkts{instance=\"$instance\",ifName=\"$ifName\"}[2m]) or irate(ifOutBroadcastPkts{instance=\"$instance\",ifName=\"$ifName\"}[2m])",
     "legendFormat": "OUT: {{ifName}}"
    }
   ]
  },
  {
   "title": "Multicast Packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{instance=\"$instance\",ifName=\"$ifName\"}[2m]) or irate(ifInMulticastPkts{instance=\"$instance\",ifName=\"$ifName\"}[2m])",
     "legendFormat": "IN: {{ifName}}"
    },
    {
     "expr": "irate(ifHCOutMulticastPkts{instance=\"$instance\",ifName=\"$ifName\"}[2m]) or irate(ifOutMulticastPkts{instance=\"$instance\",ifName=\"$ifName\"}[2m])",
     "legendFormat": "OUT: {{ifName}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(ifInErrors{instance=\"$instance\",ifName=\"$ifName\"}[2m])",
     "legendFormat": "IN: errors: {{ifName}}"
    },
    {
     "expr": "irate(ifOutErrors{instance=\"$instance\",ifName=\"$ifName\"}[2m])",
     "legendFormat": "OUT: errors: {{ifName}}"
    }
   ]
  },
  {
   "title": "Discards",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(ifInDiscards{instance=\"$instance\",ifName=\"$ifName\"}[2m])",
     "legendFormat": "IN: discards: {{ifName}}"
    },
    {
     "expr": "irate(ifInUnknownProtos{instance=\"$instance\",ifName=\"$ifName\"}[2m])",
     "legendFormat": "IN: unknown protos: {{ifName}}"
    },
    {
     "expr": "irate(ifOutDiscards{instance=\"$instance\",ifName=\"$ifName\"}[2m])",
     "legendFormat": "OUT: discards: {{ifName}}"
    }
   ]
  }
 ]
}